namespace SpriteKind {
    export const ground = SpriteKind.create()
    export const power = SpriteKind.create()
    export const boom = SpriteKind.create()
    export const enemyProjectile = SpriteKind.create()
    export const superDuperEnemy = SpriteKind.create()
    export const superEnemy = SpriteKind.create()
    export const bigBlast = SpriteKind.create()
    export const superLaser = SpriteKind.create()
}
namespace StatusBarKind {
    export const power = StatusBarKind.create()
}
sprites.onOverlap(SpriteKind.superEnemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    otherSprite.destroy()
    alien = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . d d d d d . . . . . . 
        . . . . b d d d d d b . . . . . 
        . . . . b b b b b b b . . . . . 
        . . . . . b b b b b . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    alien.setPosition(sprite.x, sprite.y)
    sprite.destroy()
    list.removeAt(list.indexOf(sprite))
    list.push(alien)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (statusbar.value >= 30) {
        bigLaser = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . 2 2 2 . . . . . . . . 
            . . . . 2 2 2 2 2 . . . . . . . 
            . . . 2 2 4 4 4 2 2 . . . . . . 
            . . 2 2 4 4 5 4 4 2 2 . . . . . 
            . . 2 2 4 5 5 5 4 2 2 . . . . . 
            . . 2 2 4 4 5 4 4 2 2 . . . . . 
            . . . 2 2 4 4 4 2 2 . . . . . . 
            . . . . 2 2 2 2 2 . . . . . . . 
            . . . . . 2 2 2 . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.bigBlast)
        bigLaser.setPosition(ship.x, ship.y)
        bigLaser.vy += -25
        statusbar.value += -30
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.enemyProjectile, function (sprite, otherSprite) {
    otherSprite.destroy()
    info.changeScoreBy(-1)
    info.changeLifeBy(-1)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (statusbar.value >= 10) {
        laser = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . 5 . . . . . . . . 
            . . . . . . . 5 . . . . . . . . 
            . . . . . . . 5 . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Projectile)
        laser.setPosition(ship.x, ship.y)
        laser.vy += -25
        statusbar.value += -10
    }
})
sprites.onOverlap(SpriteKind.power, SpriteKind.Player, function (sprite, otherSprite) {
    sprite.destroy()
    statusbar.value += 10
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    otherSprite.destroy()
    explosion = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ...............2................
        ..............242...............
        .............24442..............
        ............2445442.............
        ...........244555442............
        ..........24455155442...........
        ...........244555442............
        ............2445442.............
        .............24442..............
        ..............242...............
        ...............2................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.boom)
    explosion.setPosition(sprite.x, sprite.y)
    sprite.destroy()
    info.changeScoreBy(1)
    pause(500)
    explosion.destroy()
    list.removeAt(list.indexOf(sprite))
})
info.onCountdownEnd(function () {
    game.over(true, effects.starField)
})
sprites.onOverlap(SpriteKind.bigBlast, SpriteKind.superEnemy, function (sprite, otherSprite) {
    sprite.destroy()
    explosion = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ...............2................
        ..............242...............
        .............24442..............
        ............2445442.............
        ...........244555442............
        ..........24455155442...........
        ...........244555442............
        ............2445442.............
        .............24442..............
        ..............242...............
        ...............2................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.boom)
    explosion.setPosition(otherSprite.x, otherSprite.y)
    otherSprite.destroy()
    pause(500)
    info.changeScoreBy(1)
    explosion.destroy()
    list.removeAt(list.indexOf(otherSprite))
})
sprites.onOverlap(SpriteKind.bigBlast, SpriteKind.superDuperEnemy, function (sprite, otherSprite) {
    sprite.destroy()
    explosion = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ...............2................
        ..............242...............
        .............24442..............
        ............2445442.............
        ...........244555442............
        ..........24455155442...........
        ...........244555442............
        ............2445442.............
        .............24442..............
        ..............242...............
        ...............2................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.boom)
    explosion.setPosition(otherSprite.x, otherSprite.y)
    otherSprite.destroy()
    pause(500)
    info.changeScoreBy(1)
    explosion.destroy()
    list.removeAt(list.indexOf(otherSprite))
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.bigBlast, function (sprite, otherSprite) {
    otherSprite.destroy()
    explosion = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ...............2................
        ..............242...............
        .............24442..............
        ............2445442.............
        ...........244555442............
        ..........24455155442...........
        ...........244555442............
        ............2445442.............
        .............24442..............
        ..............242...............
        ...............2................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.boom)
    explosion.setPosition(sprite.x, sprite.y)
    sprite.destroy()
    info.changeScoreBy(1)
    pause(500)
    explosion.destroy()
    list.removeAt(list.indexOf(sprite))
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.boom, function (sprite, otherSprite) {
    info.changeScoreBy(-3)
    info.changeLifeBy(-3)
})
info.onLifeZero(function () {
    explosion = sprites.create(img`
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ...............2................
        ..............242...............
        .............24442..............
        ............2445442.............
        ...........244555442............
        ..........24455155442...........
        ...........244555442............
        ............2445442.............
        .............24442..............
        ..............242...............
        ...............2................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        ................................
        `, SpriteKind.boom)
    explosion.setPosition(ship.x, ship.y)
    game.over(false)
})
sprites.onOverlap(SpriteKind.superDuperEnemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    otherSprite.destroy()
    superAlien = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 5 5 5 5 5 . . . . . . 
        . . . . 5 d d d d d 5 . . . . . 
        . . . 5 b d d d d d b 5 . . . . 
        . . . 5 b b b b b b b 5 . . . . 
        . . . . 5 b b b b b 5 . . . . . 
        . . . . . 5 5 5 5 5 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.superEnemy)
    superAlien.setPosition(sprite.x, sprite.y)
    sprite.destroy()
    list.removeAt(list.indexOf(sprite))
    list.push(superAlien)
})
let megaAlien: Sprite = null
let power2: Sprite = null
let enemyLaser: Sprite = null
let superAlien: Sprite = null
let explosion: Sprite = null
let laser: Sprite = null
let bigLaser: Sprite = null
let alien: Sprite = null
let list: Sprite[] = []
let ship: Sprite = null
let statusbar: StatusBarSprite = null
scene.setBackgroundColor(12)
game.splash("Pilot, you charge is low.", "We found energy nearby...")
game.splash("But it's guarded by a", "swarm of hostiles.")
game.splash("Your power will be mostly", "spent fighting them.")
game.splash("This is your first combat", "run. Here are the basics:")
game.splash("A launches a regular pulse", "B shoots a big blast")
game.splash("Most go down with one pulse,", "but some are shielded.")
game.splash("Yellow shields need two.", "Red shields take three.")
game.splash("All go down with", "one big blast.")
game.splash("Which reminds me, both", "attacks cost energy.")
game.splash("Pulses use one cell.", "Blasts use three cells.")
game.splash("No power, no attacking.")
game.splash("Also, getting hit", "will drop your score.")
game.splash("1 life lost = -1 score")
game.splash("You got all that?", "Good.")
game.splash("Computer says we arrive", "in T-2_minutes.")
game.splash("Stay alive, pilot.", "We'll be there soon.")
statusbar = statusbars.create(5, 50, StatusBarKind.power)
statusbar.setColor(8, 2)
statusbar.positionDirection(CollisionDirection.Left)
statusbar.setOffsetPadding(0, 2)
info.startCountdown(120)
info.setLife(3)
ship = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..............bb................
    ...........3.bbbb.3.............
    ...........3bb11bb3.............
    ...........3bbbbbb3.............
    ...........3bbbbbb3.............
    ...........bbbddbbb.............
    ..........bbbddddbbb............
    ..........bbdfdfffbb............
    ..........bbdfdfddbb............
    ..........bbdfdfffbb............
    ..........bbdfdfdfbb............
    ..........bbdfdfffbb............
    ..........bbbbbbbbbb............
    ...........bbbbbbbb.............
    ...........eee..eee.............
    ...........e4e..e4e.............
    ............2....2..............
    ............2....2..............
    ................................
    ................................
    ................................
    `, SpriteKind.Player)
ship.setStayInScreen(true)
list = []
game.onUpdateInterval(5000, function () {
    alien = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . d d d d d . . . . . . 
        . . . . b d d d d d b . . . . . 
        . . . . b b b b b b b . . . . . 
        . . . . . b b b b b . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    alien.x = randint(16, scene.screenWidth() - 16)
    alien.y = randint(20, scene.screenHeight() - 75)
    list.push(alien)
})
game.onUpdateInterval(2000, function () {
    for (let value of list) {
        enemyLaser = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . 9 . . . . . . . . 
            . . . . . . . 9 . . . . . . . . 
            . . . . . . . 9 . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.enemyProjectile)
        enemyLaser.setPosition(value.x, value.y)
        enemyLaser.vy += 25
    }
})
game.onUpdateInterval(2000, function () {
    power2 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 1 3 1 . . . . . . . 
        . . . . . 1 1 3 1 1 . . . . . . 
        . . . . 1 1 3 1 3 1 1 . . . . . 
        . . . . 3 3 1 3 1 3 3 . . . . . 
        . . . . 1 1 3 1 3 1 1 . . . . . 
        . . . . . 1 1 3 1 1 . . . . . . 
        . . . . . . 1 3 1 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.power)
    power2.x = randint(16, scene.screenWidth() - 16)
    power2.y = randint(75, scene.screenHeight() - 20)
})
forever(function () {
    ship.x += controller.dx()
    ship.y += controller.dy()
})
game.onUpdateInterval(20000, function () {
    megaAlien = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . 2 2 2 2 2 . . . . . . 
        . . . . 2 2 2 2 2 2 2 . . . . . 
        . . . 2 2 d d d d d 2 2 . . . . 
        . . 2 2 b d d d d d b 2 2 . . . 
        . . 2 2 b b b b b b b 2 2 . . . 
        . . . 2 2 b b b b b 2 2 . . . . 
        . . . . 2 2 2 2 2 2 2 . . . . . 
        . . . . . 2 2 2 2 2 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.superDuperEnemy)
    megaAlien.x = randint(16, scene.screenWidth() - 16)
    megaAlien.y = randint(20, scene.screenHeight() - 75)
    list.push(megaAlien)
})
game.onUpdateInterval(10000, function () {
    superAlien = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . 5 5 5 5 5 . . . . . . 
        . . . . 5 d d d d d 5 . . . . . 
        . . . 5 b d d d d d b 5 . . . . 
        . . . 5 b b b b b b b 5 . . . . 
        . . . . 5 b b b b b 5 . . . . . 
        . . . . . 5 5 5 5 5 . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.superEnemy)
    superAlien.x = randint(16, scene.screenWidth() - 16)
    superAlien.y = randint(20, scene.screenHeight() - 75)
    list.push(superAlien)
})
